"""
Email Notification Lambda Function
Sends trading alerts and daily summaries via SES
"""

import json
import os
import boto3
from datetime import datetime

# Initialize SES client
ses = boto3.client('ses', region_name=os.environ.get('AWS_REGION', 'us-west-2'))
ssm = boto3.client('ssm')

def get_notification_email():
    """Get notification email from environment or Parameter Store"""
    email = os.environ.get('NOTIFICATION_EMAIL')
    if not email:
        try:
            response = ssm.get_parameter(
                Name='/trading-agent/notification-email',
                WithDecryption=False
            )
            email = response['Parameter']['Value']
        except Exception as e:
            print(f"Error getting email: {e}")
            return None
    return email

def format_recommendation_email(recommendations):
    """Format trading recommendations as HTML email"""
    
    html = """
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; }}
            .header {{ background-color: #1a73e8; color: white; padding: 20px; }}
            .recommendation {{ border: 1px solid #ddd; margin: 10px 0; padding: 15px; border-radius: 5px; }}
            .buy {{ border-left: 5px solid #34a853; }}
            .sell {{ border-left: 5px solid #ea4335; }}
            .hold {{ border-left: 5px solid #fbbc04; }}
            .indicator {{ display: inline-block; margin: 5px 10px 5px 0; }}
            .footer {{ margin-top: 20px; padding: 10px; background-color: #f5f5f5; font-size: 12px; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>🎯 Daily Trading Analysis</h1>
            <p>Market opportunities for {date}</p>
        </div>
    """.format(date=datetime.now().strftime('%B %d, %Y'))
    
    if not recommendations:
        html += """
        <div style="padding: 20px;">
            <p>No high-confidence trading opportunities identified today.</p>
            <p>Market conditions suggest holding current positions.</p>
        </div>
        """
    else:
        for rec in recommendations:
            action_class = rec['recommendation'].lower()
            
            html += f"""
            <div class="recommendation {action_class}">
                <h2>{rec['symbol']} - {rec['recommendation']}</h2>
                <p><strong>Current Price:</strong> ${rec['price']:.2f}</p>
                <p><strong>Confidence:</strong> {rec['confidence']*100:.0f}%</p>
                
                <h3>Technical Indicators:</h3>
                <div class="indicator">
                    <strong>RSI:</strong> {rec['indicators']['rsi']:.1f}
                    {'📉 Oversold' if rec['indicators']['rsi'] < 30 else '📈 Overbought' if rec['indicators']['rsi'] > 70 else ''}
                </div>
                <div class="indicator">
                    <strong>EMA 20:</strong> ${rec['indicators']['ema_20']:.2f}
                </div>
                <div class="indicator">
                    <strong>EMA 50:</strong> ${rec['indicators']['ema_50']:.2f}
                </div>
                
                <h3>Signals:</h3>
                <ul>
            """
            
            for signal in rec['signals']:
                html += f"<li>{signal.replace('_', ' ')}</li>"
            
            html += """
                </ul>
                
                <h3>Risk Management:</h3>
                <p>
                    <strong>Suggested Stop Loss:</strong> 3% below entry<br>
                    <strong>Target Profit:</strong> 5-8% above entry<br>
                    <strong>Max Position Size:</strong> 2% of portfolio
                </p>
            </div>
            """
    
    html += """
        <div class="footer">
            <p><strong>Disclaimer:</strong> This is an automated analysis for educational purposes only. 
            Not financial advice. Always do your own research and consult with financial advisors.</p>
            <p>Generated by AI Trading Agent | Powered by AWS Bedrock AgentCore</p>
        </div>
    </body>
    </html>
    """
    
    return html

def format_alert_email(alert_type, data):
    """Format specific alert emails"""
    
    subject_map = {
        'high_confidence_opportunity': '🎯 High Confidence Trading Opportunity',
        'stop_loss_triggered': '⚠️ Stop Loss Triggered',
        'take_profit_reached': '✅ Take Profit Target Reached',
        'daily_summary': '📊 Daily Trading Summary'
    }
    
    subject = subject_map.get(alert_type, '📬 Trading Alert')
    
    if alert_type == 'high_confidence_opportunity':
        body = format_recommendation_email([data])
    elif alert_type == 'daily_summary':
        body = format_recommendation_email(data.get('recommendations', []))
    else:
        body = f"""
        <html>
        <body>
            <h2>{subject}</h2>
            <pre>{json.dumps(data, indent=2)}</pre>
        </body>
        </html>
        """
    
    return subject, body

def send_email(to_email, subject, html_body):
    """Send email via SES"""
    
    try:
        response = ses.send_email(
            Source=to_email,  # Must be verified in SES
            Destination={'ToAddresses': [to_email]},
            Message={
                'Subject': {'Data': subject},
                'Body': {
                    'Html': {'Data': html_body}
                }
            }
        )
        
        return {
            'success': True,
            'message_id': response['MessageId']
        }
    except Exception as e:
        return {
            'success': False,
            'error': str(e)
        }

def lambda_handler(event, context):
    """Lambda handler for email notifications"""
    
    # Get notification email
    to_email = get_notification_email()
    if not to_email:
        return {
            'statusCode': 500,
            'body': json.dumps({'error': 'Notification email not configured'})
        }
    
    # Parse input
    body = event.get('body', '{}')
    if isinstance(body, str):
        body = json.loads(body)
    
    alert_type = body.get('alert_type', event.get('alert_type', 'daily_summary'))
    data = body.get('data', event.get('data', {}))
    
    # Format email
    subject, html_body = format_alert_email(alert_type, data)
    
    # Send email
    result = send_email(to_email, subject, html_body)
    
    if result['success']:
        return {
            'statusCode': 200,
            'body': json.dumps({
                'message': 'Email sent successfully',
                'message_id': result['message_id']
            })
        }
    else:
        return {
            'statusCode': 500,
            'body': json.dumps({
                'error': 'Failed to send email',
                'details': result['error']
            })
        }
